/* ElectricBlaze · Instagram feed for plain HTML sites.
   Generated by `npx electricblaze add instagram-feed`. Restyle or rewrite freely.

   Usage:
     <link rel="stylesheet" href="electricblaze/instagram-feed.css">
     <div data-eb-feed="instagram" data-limit="8"></div>
     <script src="electricblaze/instagram.demo.js"></script>
     <script src="electricblaze/instagram-feed.js" defer></script>

   Data comes from window.ElectricBlazeFeeds.instagram (the demo file above) or, when
   data-src is set, from that JSON URL. Feed shape: electricblaze/feed.d.ts (schema v1). */
(function () {
  var esc = function (s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  };

  function render(feed, posts, showHeader) {
    var o = feed.origin;
    var html = '<section class="eb-feed" aria-label="Instagram posts by @' + esc(o.name) + '">';
    if (showHeader) {
      html += '<header class="eb-feed__header">';
      if (o.avatarUrl) html += '<img class="eb-feed__avatar" src="' + esc(o.avatarUrl) + '" alt="" width="40" height="40">';
      html += '<a class="eb-feed__handle" href="' + esc(o.url) + '" target="_blank" rel="noopener noreferrer">@' + esc(o.name) + "</a>";
      if (feed.demo) html += '<span class="eb-feed__demo" title="Sample posts. Connect an Instagram account to show real ones.">demo feed</span>';
      html += "</header>";
    }
    html += '<ul class="eb-feed__grid">';
    posts.forEach(function (p) {
      var m = p.media && p.media[0];
      var badge = p.type === "video" ? (p.format === "reel" ? "Reel" : "Video") : p.type === "carousel" ? p.media.length + " photos" : "";
      html += '<li class="eb-feed__item"><a href="' + esc(p.url) + '" target="_blank" rel="noopener noreferrer" title="' + esc(p.text) + '">';
      html += '<img src="' + esc(p.thumbnailUrl) + '" alt="' + esc((m && m.alt) || p.text) + '" loading="lazy"' + (m && m.width ? ' width="' + m.width + '" height="' + m.height + '"' : "") + ">";
      if (badge) html += '<span class="eb-feed__badge">' + esc(badge) + "</span>";
      html += "</a></li>";
    });
    return html + "</ul></section>";
  }

  function mount(el) {
    var limit = Number(el.getAttribute("data-limit") || 8);
    var formats = (el.getAttribute("data-formats") || "").split(",").map(function (s) { return s.trim(); }).filter(Boolean);
    var showHeader = el.getAttribute("data-header") !== "false";
    var src = el.getAttribute("data-src");
    var ready = src
      ? fetch(src).then(function (r) { if (!r.ok) throw new Error("ElectricBlaze feed " + r.status); return r.json(); })
      : Promise.resolve(window.ElectricBlazeFeeds && window.ElectricBlazeFeeds.instagram);
    ready.then(function (feed) {
      if (!feed) throw new Error("No feed data: include electricblaze/instagram.demo.js or set data-src.");
      var posts = feed.posts;
      if (formats.length) posts = posts.filter(function (p) { return formats.indexOf(p.format) !== -1; });
      el.innerHTML = render(feed, posts.slice(0, limit), showHeader);
    }).catch(function (e) {
      el.innerHTML = '<p class="eb-feed__error">' + esc(e.message) + "</p>";
    });
  }

  var els = document.querySelectorAll('[data-eb-feed="instagram"]');
  for (var i = 0; i < els.length; i++) mount(els[i]);
})();
