// ElectricBlaze · Instagram feed (Server Component, Next.js App Router).
// Generated by `npx electricblaze add instagram-feed`. Restyle or restructure freely;
// the data shape is documented in lib/eb/feed.d.ts and never changes under you.

import { getInstagramFeed, type FeedOptions } from "../../lib/eb/instagram";
import styles from "./InstagramFeed.module.css";

type Props = FeedOptions & {
  /** Show the @handle header. Default true. */
  header?: boolean;
};

export default async function InstagramFeed({ limit = 8, formats, header = true }: Props) {
  const feed = await getInstagramFeed({ limit, formats });

  return (
    <section className={styles.feed} aria-label={`Instagram posts by @${feed.origin.name}`}>
      {header && (
        <header className={styles.header}>
          {feed.origin.avatarUrl && (
            // Plain <img>: thumbnails come from ElectricBlaze's CDN, which is not in next.config images.remotePatterns.
            <img className={styles.avatar} src={feed.origin.avatarUrl} alt="" width={40} height={40} />
          )}
          <a href={feed.origin.url} target="_blank" rel="noopener noreferrer" className={styles.handle}>
            @{feed.origin.name}
          </a>
          {feed.demo && (
            <span className={styles.demo} title="Sample posts. Connect an Instagram account to show real ones.">
              demo feed
            </span>
          )}
        </header>
      )}

      <ul className={styles.grid}>
        {feed.posts.map((post) => (
          <li key={post.id} className={styles.item}>
            <a href={post.url} target="_blank" rel="noopener noreferrer" title={post.text}>
              <img
                src={post.thumbnailUrl}
                alt={post.media[0]?.alt ?? post.text}
                loading="lazy"
                width={post.media[0]?.width}
                height={post.media[0]?.height}
              />
              {post.type === "video" && (
                <span className={styles.badge}>{post.format === "reel" ? "Reel" : "Video"}</span>
              )}
              {post.type === "carousel" && (
                <span className={styles.badge}>
                  {post.media.length} {post.media.every((m) => m.mime.startsWith("image/")) ? "photos" : "items"}
                </span>
              )}
            </a>
          </li>
        ))}
      </ul>
    </section>
  );
}
