// ElectricBlaze · Instagram feed loader for Next.js (App Router).
// Generated by `npx electricblaze add instagram-feed`. Edit freely; re-running add never overwrites your changes.
//
// Status (0.1): returns the bundled demo feed (feed.demo === true). The JSON API behind
// ELECTRICBLAZE_API_KEY ships in 0.2; the endpoint below is its contract and does not answer
// yet, so leave the key unset until then. Real posts today come from the ElectricBlaze widget
// embed (https://electricblaze.com), which does not go through this loader.

import type { Feed, Post } from "./feed";
import demo from "./demo/instagram.json";

const API = process.env.ELECTRICBLAZE_API_URL ?? "https://api.electricblaze.com/v1";

export type FeedOptions = {
  /** Max posts to return. Default 8. */
  limit?: number;
  /** Keep only these formats, e.g. ["reel"] or ["post"]. */
  formats?: Post["format"][];
};

export async function getInstagramFeed(opts: FeedOptions = {}): Promise<Feed> {
  const key = process.env.ELECTRICBLAZE_API_KEY;
  let feed = demo as Feed;

  if (key) {
    const url = new URL(`${API}/feeds/instagram`);
    if (opts.limit) url.searchParams.set("limit", String(opts.limit));
    if (opts.formats?.length) url.searchParams.set("formats", opts.formats.join(","));
    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${key}` },
      next: { revalidate: 3600 },
    } as RequestInit);
    if (!res.ok) {
      throw new Error(`ElectricBlaze API responded ${res.status}. Run: npx electricblaze doctor`);
    }
    feed = (await res.json()) as Feed;
  }

  let posts = feed.posts;
  if (opts.formats?.length) posts = posts.filter((p) => opts.formats!.includes(p.format));
  posts = posts.slice(0, opts.limit ?? 8);
  return { ...feed, posts };
}
